disabled_rules:
  - trailing_whitespace
  - line_length
  
opt_in_rules:
  - empty_count
  - explicit_init
  - explicit_type_interface
  - force_unwrapping
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - closure_spacing
  - operator_usage_whitespace
  
excluded:
  - Pods
  - .build
  - DerivedData
  - Package.swift
  
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  
file_length:
  warning: 500
  error: 1000
  
function_body_length:
  warning: 50
  error: 100
  
type_body_length:
  warning: 300
  error: 500
  
cyclomatic_complexity:
  warning: 10
  error: 20
  
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - db
    - x
    - y
    - z
    
reporter: "xcode"
